version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"  

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'    
    ports:
      - '3000:3000'
    volumes:
      - '.:/pfc-master'
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db
