# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
<<<<<<< HEAD

default: &default
=======
default:
>>>>>>> 6ac270ee23c708b481e300f6ea19111745320983
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: db
  #socket: /tmp/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  database: pfc-master_development
  pool: 5
  username: root
  password: password
  host: localhost
<<<<<<< HEAD
=======

>>>>>>> 6ac270ee23c708b481e300f6ea19111745320983

test:
  adapter: mysql2
  encoding: utf8
  database: pfc-master_test
  pool: 5
  username: root
  password: password
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: pfc-master_production
  username: root
  password: password
  host: localhost
<<<<<<< HEAD
  #socket: /var/lib/mysql/mysql.sock
=======
  # socket: /var/lib/mysql/mysql.sock
>>>>>>> 6ac270ee23c708b481e300f6ea19111745320983
