default:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: db
  #socket: /tmp/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  database: pfc-master_development
  pool: 5
  username: root
  password: password
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: pfc-master_test
  pool: 5
  username: 'root'
  password: password
  host: '127.0.0.1'

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: pfc-master_production
  username: root
  password: password
  host: localhost
  socket: /var/lib/mysql/mysql.sock
