# MySQL. Versions 5.1.10 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  host: db
  #socket: /tmp/mysql.sock

development:
  adapter: mysql2
  encoding: utf8
  database: pfc-master_development
  pool: 5
  username: root
  password: password
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: pfc-master_test
  pool: 5
  username: 'root'
  password: password
  host: '127.0.0.1'

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: pfc-master_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  socket: /var/lib/mysql/mysql.sock
